version: "3.8"

services:
  auth-rp-stub:
    container_name: di-auth-stub-relying-party_auth-rp-stub
    ports:
      - "8080:8080"
    build:
      context: .
    env_file:
      - .env
    restart: on-failure
