resource_types:
  - name: cf-cli
    type: docker-image
    source:
      repository: nulldriver/cf-cli-resource

resources:
  - name: di-auth-stub-relying-party
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/di-auth-stub-relying-party.git
      ignore_paths:
        - ci/pipeline.yaml
      branch: main

  - name: pipeline-src
    type: git
    icon: github
    source:
      uri: https://github.com/alphagov/di-auth-stub-relying-party.git
      paths:
        - ci/pipeline.yaml
      branch: main

  - name: di-auth-stub-relying-party-upload-sandbox
    type: cf-cli
    icon: cloud-upload
    source:
      api: https://api.london.cloud.service.gov.uk
      username: ((cf-username))
      password: ((cf-password))
      org: gds-digital-identity-authentication
      space: sandbox

  - name: di-auth-stub-relying-party-upload-build
    type: cf-cli
    icon: cloud-upload
    source:
      api: https://api.london.cloud.service.gov.uk
      username: ((cf-username))
      password: ((cf-password))
      org: gds-digital-identity-authentication
      space: build

  - name: di-auth-stub-relying-party-upload-build-s2
    type: cf-cli
    icon: cloud-upload
    source:
      api: https://api.london.cloud.service.gov.uk
      username: ((cf-username))
      password: ((cf-password))
      org: gds-digital-identity-authentication
      space: build

jobs:
  - name: update-pipeline
    plan:
      - get: pipeline-src
        trigger: true
      - set_pipeline: di-auth-stub-relying-party
        file: pipeline-src/ci/pipeline.yaml
  
  - name: deploy-app
    plan:
    - get: di-auth-stub-relying-party
      trigger: true
    - task: build
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: gradle
            tag: 6.8.3-jdk15
        inputs:
          - name: di-auth-stub-relying-party
        outputs:
          - name: di-auth-stub-relying-party-zip
        run:
          path: /bin/bash
          args:
            - -euc
            - |
              cd di-auth-stub-relying-party
              gradle --no-daemon build
              cp build/distributions/di-auth-stub-relying-party.zip ../di-auth-stub-relying-party-zip/
    - put: di-auth-stub-relying-party-upload-sandbox
      params:
        command: push
        app_name: di-auth-stub-relying-party-sandbox
        manifest: di-auth-stub-relying-party/manifest.yml
        path: di-auth-stub-relying-party-zip/di-auth-stub-relying-party.zip
        environment_variables:
          OP_BASE_URL: ((sandbox-op-base-url))
          CLIENT_PRIVATE_KEY: ((sandbox-client-private-key))
    - put: di-auth-stub-relying-party-upload-build
      params:
        command: push
        app_name: di-auth-stub-relying-party-build
        manifest: di-auth-stub-relying-party/manifest.yml
        path: di-auth-stub-relying-party-zip/di-auth-stub-relying-party.zip
        environment_variables:
          OP_BASE_URL: ((build-op-base-url))
          CLIENT_PRIVATE_KEY: ((build-client-private-key))
    - put: di-auth-stub-relying-party-upload-build-s2
      params:
        command: push
        app_name: di-auth-stub-relying-party-build-s2
        manifest: di-auth-stub-relying-party/manifest.yml
        path: di-auth-stub-relying-party-zip/di-auth-stub-relying-party.zip
        environment_variables:
          OP_BASE_URL: ((build-op-base-url))
          CLIENT_PRIVATE_KEY: ((build-client-private-key))


