name: On merge

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  run-checks:
    uses: ./.github/workflows/run-checks.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SAM_APP_VALIDATE_ROLE_ARN: ${{ secrets.SAM_APP_VALIDATE_ROLE_ARN }}